spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    publisher-confirms: false
    publisher-returns: false

server:
  port: 8081
  servlet:
    session:
      timeout: 30m
